services:

  db:
    image: postgres:16-alpine3.19
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=measures

volumes:
  db:
    driver: local